from typing import Protocol
from uuid import UUID

from .models import MemoryRecord, SemanticFact


class WorkingMemoryStore(Protocol):
    async def put(self, run_id: UUID, key: str, value: str) -> None: ...
    async def get(self, run_id: UUID, key: str) -> str | None: ...
    async def clear(self, run_id: UUID) -> None: ...


class EpisodicStore(Protocol):
    async def add(self, record: MemoryRecord) -> None: ...
    async def for_run(self, run_id: UUID) -> list[MemoryRecord]: ...


class SemanticStore(Protocol):
    async def add(self, fact: SemanticFact) -> None: ...
    async def list(self) -> list[SemanticFact]: ...
