from typing import Protocol
from uuid import UUID

from .models import Goal, GoalStatus


class GoalRepository(Protocol):
    async def create(
        self,
        title: str,
        description: str = "",
        priority: int = 0,
        constraints: list[str] | None = None,
        success_criteria: list[str] | None = None,
        metadata: dict[str, str] | None = None,
    ) -> Goal: ...
    async def get(self, goal_id: UUID) -> Goal: ...
    async def list(self) -> list[Goal]: ...
    async def update_status(self, goal_id: UUID, status: GoalStatus) -> Goal: ...
    async def attach_run(self, goal_id: UUID, run_id: UUID) -> Goal: ...
    async def mark_completed(self, goal_id: UUID) -> Goal: ...
    async def mark_failed(self, goal_id: UUID) -> Goal: ...
